<?php namespace Cb\Pgmware\Updates;

use Seeder;
use DB;
use  Cb\Pgmware\Models\Location;
use  Cb\Pgmware\Models\LocationAddress;

class Seeder10121 extends Seeder
{
    public function run()
    {
       //Location::truncate();
       DB::table('cb_pgmware_locations')->delete();

       Location::create(['id' => 122,'name' => 'Riverside Speedway','slug' => 'riverside-speedway','description' => 'Riverside International Speedway is a 1/3-mile oval situated near the town of Antigonish in Nova Scotia, Canada. It was opened in 1969, with the NASCAR Busch East Series subsequently racing at the venue. In 2006 the total complex was comprehensively renovated and modernized.
<br><br>
Riverside International Speedway regularly promotes race meetings, including NASCAR’s Canadian Tire Series and the ProStock-Tour. In addition, NASCAR Driving Experiences are offered, while race teams may hire the oval for private testing.','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 1]);
Location::create(['id' => 125,'name' => 'Edmonton International Raceway','slug' => 'edmonton-international-raceway','description' => 'Edmonton International Raceway is a short oval situated near Wetaskiwin in Alberta, Canada. Races for some of NASCAR’s lesser series and stock cars are promoted by the circuit, which also caters for driver training activities, stock car experiences for the public, and corporate events. Companies are offered special packages, which include stock cars test activities, single/group photo sessions and BBQs. Hospitality evenings during race meetings may also be booked by corporates.','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 2]);
Location::create(['id' => 126,'name' => 'Gimli Motorsports Park','slug' => 'gimli-motorsports-park','description' => 'Gimli Motorsports Park lies west of the town of the same name in Canada’s Manitoba province. The facility comprises a 1.3-mile road course, a kart track and a motocross course. Portions of the circuit pass over a former military airfield currently used for civilian purposes. The first races were staged here in 1971. Gimli is used primarily for club racing. Beside the race track, the venue also features an IHRA-licensed drag strip, which is, though, under separate management.','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 3]);
Location::create(['id' => 127,'name' => 'ICAR','slug' => 'icar','description' => 'While many circuits in Europe and North America have their roots in disused airfields, the International Center of Advanced Racing (ICAR) is situated on the site of Montreal\'s Mirabel Airport, which until recently boasted the world\'s largest airport surface area.
<br><br>
The facility consists of a road circuit, which can be configured in a variety of layouts, a drag strip, an autocross course, a drift park, a driver safety center and a kart circuit, the latter designed by former Formula 1 world champion Jacques Villeneuve. ICAR’s race driver academy is also named after the Quebec-born race driver.','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 4]);
Location::create(['id' => 128,'name' => 'Mecaglisse','slug' => 'mecaglisse','description' => 'Mecaglisse is a motorsport complex situated near Notre-Dame-de-la-Merci in Quebec, Canada, approximately 90 minutes north of Montréal. Various on- and off-road courses suitable for both cars and motorcycles make Mecaglisse an ideal venue for test drives, product presentations and launches, and corporate events.
<br><br>
Motorsport can be practiced at Mecaglisse throughout the year, with an asphalt road course, gravel rally stage, a sand track and off-road course for ATVs and quads catering for summer activities. During winter months ice and snow track activities are catered for. In addition, Mecaglisse offers track days and driver training under the tutelage of experienced instructors, whether on- or off-road; two wheels or four.','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 5]);
Location::create(['id' => 129,'name' => 'Mission Raceway Park','slug' => 'mission-raceway-park','description' => 'Mission Raceway Park is situated approximately an hour\'s drive east of Vancouver. The circuit lies on the bank of the Fraser River, and consists of a classic road-racing course, plus a drag strip, a kart track and a motocross circuit. MRP is home to various motorsport clubs, who operate this multi-purpose venue on a combined basis. 
<br><br>
It was opened in March 1992, initially as a driver safety center, with MRP regularly hosting race meetings from 1994 onwards. The drag strip has on nine occasions been designated NHRA Division Six Track of the Year.','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 6]);
Location::create(['id' => 130,'name' => 'Race City Motorsport Park','slug' => 'race-city-motorsport-park','description' => null,'timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 7]);
Location::create(['id' => 131,'name' => 'Sanair','slug' => 'sanair','description' => 'Sanair is a motorsport complex in St. Pie in Canada’s Quebec province, approximately 40 minutes east of Montréal. The venue offers a variety of different circuit layouts, a tri-oval, a drag strip and a small off-road area suitable for ATVs. Between April and September the drag strip promotes weekly drag races, with drift contests, auto shows and NASCAR races on the tri-oval also proving popular. During ‘free’ periods, track days are offered, including ice and snow events in winter. In addition, a variety of driving schools offer courses.','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 8]);
Location::create(['id' => 140,'name' => 'Mosport Raceway','slug' => 'mosport-raceway','description' => 'Mosport International Raceway is a multi-purpose facility situated to the north of Bowmanville, Ontario, and was opened in 1961. Apart from its famous road racing circuit – which hosted Formula 1 world championship grands prix between 1967 and 1977 – the venue encompasses an oval circuit, a kart track and a driver safety center. Triple world champion Jackie Stewart won two grands prix (1971 and 1972) at the circuit then known as Mosport Park to become its most successful driver.
<br><br>
In 2001 the circuit was resurfaced and widened to comply with FIA standards although the circuit’s traditional characteristics were retained notwithstanding these upgrades. The American Le Mans Series has regularly visited Mosport since the series\' inception.','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 9]);
Location::create(['id' => 145,'name' => 'Shannonville Motorsport Park','slug' => 'shannonville-motorsport-park','description' => 'Shannonville Motorsport Park is situated midway between Toronto and Montréal. Mainly used for testing, the circuit originally consisted of a dirt oval, which was later extended to include the so-called Nelson road racing circuit. The Fabi course, whose back straight doubles as a drag strip, was subsequently built to the north of the Nelson course. The two circuits can be combined to provide numerous layout permutations.
<br><br>
Beside the Canadian Superbike Championship, which regular visits Shannonville Motorsport Park, the circuit hosts a variety of drag racing events.','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 10]);
Location::create(['id' => 151,'name' => 'Calabogie Motorsports Park','slug' => 'calabogie-motorsports-park','description' => 'The Calabogie track near Ottawa, Ontario has been designed to provide a challenging, safe and charismatic venue for amateur and club level performance driving enthusiasts. The layout and design of the Calabogie course was, from the outset, designed with this customer in mind, to provide them with the high-speed challenges they would not be able to find on public roads or even other comparable closed courses.
<br><br>
Calabogie was built in 2006 and has been recognised as one of the most aesthetically pleasing driving facilities in North America thanks to the proximity of its woodlands, its adherence to the natural topography of the site and the sheer drama of its course design. The Park has received approval to begin installing solar panels on the rooftops of the Paddock buildings in an effort to combat air pollution by creating an alternative source of energy for the Park and surrounding area','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 11]);
Location::create(['id' => 155,'name' => 'Autodrome Saint-Eustache','slug' => 'autodrome-saint-eustache','description' => 'The Autodrome Saint-Eustache is a motorsport facility in Quebec, not far from the metropolis of Montreal. Opened in 1965, the circuit is a hybrid circuit, which consists of a 0.4-mile oval and a street circuit of about one mile in length.
<br><br>
Every week, the oval hosts races in the Whelen All-American Series, which is sanctioned by NASCAR. As well as stock cars, dragsters, motorbikes and karts can often be found on the track.','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 12]);
Location::create(['id' => 159,'name' => 'Atlantic Motorsport Park','slug' => 'atlantic-motorsport-park','description' => 'The Atlantic Motorsport Park, which was built in 1974 in Shubenacadie, is an undulating track located in the forests of Nova Scotia, and is guaranteed to set the pulse of any motorsport fan racing. Canadian motorsport legend Gilles Villeneuve set the current track record of 60.00 seconds here in a Formula Atlantic race in 1975.
<br><br>
In the 1970s the Atlantic Motorsport Park hosted such events as the popular NASCAR series. Since then, the circuit has been the venue for many major events, including the Canadian Superbike Championship and country and western festivals. Since it was opened, the AMP has been run by a group of volunteer motorsport fans and belongs exclusively to its membership club.','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 13]);
Location::create(['id' => 161,'name' => 'Toronto Motorsports Park','slug' => 'toronto-motorsports-park','description' => 'Toronto Motorsports Park is situated approximately 120 kilometers south of Canada\'s largest city, in close proximity to the world-famous Niagara Falls. The venue, first used in 1955, consists of a road-racing course approximately three kilometers in length, and a motocross circuit plus drag strip.
<br><br>
TMP is open to all motorsport enthusiasts – be they on two wheels or four – throughout the year, with beginners being offered lessons by experienced instructors. Skilled amateurs and semi-professional drivers alike consider this circuit to be truly challenging.','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 14]);

Location::create(['id' => 275,'name' => 'Nürburgring','slug' => 'nuerburgring','description' => 'One of the most famous racetracks in Europe, the N&uuml;rburgring in the Eifel region of Germany was opened as a race and test track in 1927, and retained its original form until 1982. The legendary Nordschleife is still largely unchanged today. The original S&uuml;dschleife was replaced with a modern Grand Prix circuit in 1984. Since then, its easily modifiable layout has made it one of the best-known Formula One venues in the world. The first winner on the new circuit was Alain Prost, who won in the same year as the track was opened. Since 2007, Formula One races have alternated on a yearly basis with the Hockenheimring.
<br><br>
The Grand Prix circuit is still merged with the Nordschleife for certain endurance races. This variant produces the longest permanent racetrack in the world and hosts the iconic 24-hour race, which regularly attracts well over 100,000 spectators. It is still possible for members of the public to pit their wits against the Nordschleife, at a nominal cost.','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 15]);

Location::create(['id' => 1044,'name' => 'Atlanta Motorsports Park','slug' => 'atlanta-motorsports-park','description' => 'Atlanta Motorsports Park is not only a brand new circuit – it is also the first environmentally friendly motorsport facility, and was constructed according to ecologically sustainable principles. The circuit is situated outside Dawsonville in Georgia, having been designed by the German circuit architect Hermann Tilke. The technically challenging layout is characterized by altitude changes, fast straights, and a variety of interesting corners.
<br><br>
Two corners pay homage to famous European circuits: the Nürburgring’s legendary Karussel, with Eau Rouge representing Belgium’s Spa-Francorchamps circuit. The circuit is owned by a private club, and is suitable for automobiles, motorcycles and karts. However, it is best suited to corporate events.','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 16]);
Location::create(['id' => 1045,'name' => 'Dover International Speedway','slug' => 'dover-international-speedway','description' => 'Dover International Speedway is situated in the eponymous town in the US State of Delaware. The one-mile oval was opened in 1966, and is viewed as one of NASCAR’s classic circuits. A unique feature is that the surface material is concrete - not asphalt - and is thus extremely tough on race cars, and hence its nickname of ‘The Monster Mile’.
<br><br>
Although the IndyRacing League visited here at the end of the 1990s, ‘The Monster Mile’ is viewed primarily as a NASCAR circuit. During non-sporting periods, Dover International Raceway is available for hire for corporate events and small group activities such as, for example, Drive Experiences.','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 17]);


Location::create(['id' => 97,'name' => 'Circuit de Spa-Francorchamps','slug' => 'circuit-de-spa-francorchamps','description' => 'The circuit in the Ardennes is one of motor racing’s absolute classics, having, apart from a few exceptions in the 70s and 80s, annually hosted the Belgian Grand Prix since Formula 1’s inception. The first winner was Juan Manuel Fangio, who won the 1950 race with an Alfa Romeo. The first car race was held at Spa-Francorchamps in 1922, although at that early stage the circuit used mainly public roads.
<br><br>
The Spa-Francorchamps of today is a modern grand prix circuit which draws on few of the original track’s sectors. However, its remains ultra-fast, with major changes in elevation, high g-forces and daunting corners such as Eau Rouge combining to make it one of motorsport’s most challenging circuits. The record-setting world champion Michael Schumacher made his debut here in 1991, celebrating his maiden Formula 1 victory at the circuit exactly a year later.','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 18]);
Location::create(['id' => 99,'name' => 'Circuit Zolder','slug' => 'circuit-zolder','description' => 'The Circuit Zolder, situated in the north-east of Belgium, was opened in 1963 by the local motor club, and has since developed into an internationally-recognized motorsport complex. Between 1973 and 1984 the circuit replaced Spa, with the first winner of the Belgian Grand Prix at the Circuit Zolder being Jackie Stewart with a Tyrrell-Ford.
<br><br>
After Formula 1 returned to Spa, Zolder hosted a wide spectrum of motorsport categories. Beside Benelux racing championships, the circuit has attracted the DTM, WTCC and ChampCar. In addition, the circuit staged rounds of the FIA GT Championship on a mildly revised version of the circuit.','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 19]);
Location::create(['id' => 101,'name' => 'Circuit Jules Tacheny Mettet','slug' => 'circuit-jules-tacheny-mettet','description' => 'The Circuit Jules Tacheny near Mettet in Belgium’s Namur province is the country’s third permanent circuit, having opened in 2010. The circuit is used for smaller events and training purposes, and is not aimed at categories such as Formula 1. The Belgian Superbike Championship is one of the series to its host rounds at this circuit.
<br><br>
The forerunner of this recently-established complex was a fifties street circuit which hosted a number of Formula 2 rounds, with such names as Stirling Moss and Alberto Ascari being amongst the winners. A difficult-to-master corner sequence on the current circuit was modelled after Laguna Seca’s famous \"Corkscrew\". ','timezone_id' => 1,'country_id'=>85, 'open_from' => 0,'open_to' => 0,'lunch_from' => 0,'lunch_to' => 0,'restaurant' => 0,'medical' => 0,'fuel' => 0,'noise' => 0,'address_id' => 19]);


       LocationAddress::create(['id' =>  1,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);
       LocationAddress::create(['id' =>  2,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);
       LocationAddress::create(['id' =>  3,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);
       LocationAddress::create(['id' =>  4,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);
       LocationAddress::create(['id' =>  5,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);
       LocationAddress::create(['id' =>  6,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);
       LocationAddress::create(['id' =>  7,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);
       LocationAddress::create(['id' =>  8,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);
       LocationAddress::create(['id' =>  9,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);
       LocationAddress::create(['id' => 10,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);
       LocationAddress::create(['id' => 11,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);
       LocationAddress::create(['id' => 12,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);
       LocationAddress::create(['id' => 13,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);
       LocationAddress::create(['id' => 14,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);
       LocationAddress::create(['id' => 15,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);

       LocationAddress::create(['id' => 16,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);
       LocationAddress::create(['id' => 17,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);
       LocationAddress::create(['id' => 18,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);
       LocationAddress::create(['id' => 19,'name' => '--','street' => '-------','additional' => '-','zip' => '-','city' => '--','gps_lat' => 0,'gps_lon' => 0, 'phone'=>'--']);


    }
}